from decimal import Decimal

ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "admin"

REGISTRY_CATEGORY_NAME = "Category"
REGISTRY_CREDENTIAL_SERVICE = "Service"
REGISTRY_CREDENTIAL_USERNAME = "Username"
REGISTRY_CREDENTIAL_PASSWORD = "Password"
REGISTRY_DOCUMENT_CONTENT = "Text"
REGISTRY_DOCUMENT_FILENAME = "filename.txt"
REGISTRY_DOCUMENT_FILETYPE = "text/plain"
REGISTRY_DOCUMENT_NAME = "Document"
REGISTRY_DOCUMENT_NAME = "Document"

FINANCE_ACCOUNT_NAME = "Test Account"
FINANCE_LINE_AMOUNT = Decimal(25)
FINANCE_LINE_SUMMARY = "Summary of Line"
FINANCE_TRANSACTION_SUMMARY = "Summary of Transaction"

USER_EMAIL = "user@example.com"
USER_PASSWORD = "user"
